[1mWARNING![0m The following scripts are not being run: ['p2p-acceptblock.py', 'sendheaders.py', 'p2p-fullblocktest.py', 'bitcoin_cli.py', 'example_test.py', 'dbcrash.py', 'p2p-compactblocks.py', 'p2p-segwit.py', 'bip68-112-113-p2p.py', 'bip9-softforks.py']. Check the test lists in test_runner.py.
.
[1mmempool_packages.py[0m failed, Duration: 1 s

[1mstdout:
[0m/var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/mempool_packages_225
2017-11-30 23:22:20.277000 TestFramework (INFO): Initializing test directory /var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/mempool_packages_225
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
2017-11-30 23:22:20.630000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 256, in start_nodes
    node.wait_for_rpc_connection()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 87, in wait_for_rpc_connection
    assert self.process.poll() is None, "ravend exited with status %i during initialization" % self.process.returncode
AssertionError: ravend exited with status 1 during initialization

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 121, in main
    self.setup_network()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 200, in setup_network
    self.setup_nodes()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 215, in setup_nodes
    self.start_nodes()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 259, in start_nodes
    self.stop_nodes()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 275, in stop_nodes
    node.stop_node()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 120, in stop_node
    self.stop()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 69, in __getattr__
    assert self.rpc_connected and self.rpc is not None, "Error: no RPC connection"
AssertionError: Error: no RPC connection
2017-11-30 23:22:20.648000 TestFramework (INFO): Stopping nodes


[1mstderr:
[0mError: Unable to start HTTP server. See debug log for details.
Error: Unable to start HTTP server. See debug log for details.
Traceback (most recent call last):
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/mempool_packages.py", line 243, in <module>
    MempoolPackagesTest().main()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 145, in main
    self.stop_nodes()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 275, in stop_nodes
    node.stop_node()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 120, in stop_node
    self.stop()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 69, in __getattr__
    assert self.rpc_connected and self.rpc is not None, "Error: no RPC connection"
AssertionError: Error: no RPC connection


......
[1mmaxuploadtarget.py[0m failed, Duration: 4 s

[1mstdout:
[0m/var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/maxuploadtarget_226
2017-11-30 23:22:20.274000 TestFramework (INFO): Initializing test directory /var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/maxuploadtarget_226
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
2017-11-30 23:22:22.015000 TestFramework.mininode (INFO): Connecting to Raven Node: 127.0.0.1:12808
2017-11-30 23:22:22.016000 TestFramework.mininode (INFO): Connecting to Raven Node: 127.0.0.1:12808
2017-11-30 23:22:22.016000 TestFramework.mininode (INFO): Connecting to Raven Node: 127.0.0.1:12808
message.nVersion: 70015
on_verack msg_verack()
message.nVersion: 70015
on_verack msg_verack()
message.nVersion: 70015
on_verack msg_verack()
2017-11-30 23:22:23.878000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 122, in main
    self.run_test()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/maxuploadtarget.py", line 103, in run_test
    assert_equal(test_nodes[0].block_receive_map[big_old_block], i+1)
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/util.py", line 39, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(0 == 1)
2017-11-30 23:22:23.885000 TestFramework (INFO): Stopping nodes
2017-11-30 23:22:24.476000 TestFramework (WARNING): Not cleaning up dir /var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/maxuploadtarget_226
2017-11-30 23:22:24.477000 TestFramework (ERROR): Test failed. Test logging available at /var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/maxuploadtarget_226/test_framework.log


[1mstderr:
[0m

...........................
[1mbip68-sequence.py[0m failed, Duration: 17 s

[1mstdout:
[0m/var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/bip68-sequence_224
2017-11-30 23:22:21.451000 TestFramework (INFO): Initializing test directory /var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/bip68-sequence_224
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
2017-11-30 23:22:22.917000 TestFramework (INFO): Running test disable flag
2017-11-30 23:22:23.070000 TestFramework (INFO): Running test sequence-lock-confirmed-inputs
2017-11-30 23:22:37.360000 TestFramework (INFO): Running test sequence-lock-unconfirmed-inputs
2017-11-30 23:22:38.157000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 122, in main
    self.run_test()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/bip68-sequence.py", line 38, in run_test
    self.test_sequence_lock_unconfirmed_inputs()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/bip68-sequence.py", line 316, in test_sequence_lock_unconfirmed_inputs
    assert(tx3.hash not in mempool)
AssertionError
2017-11-30 23:22:38.157000 TestFramework (INFO): Stopping nodes
2017-11-30 23:22:38.647000 TestFramework (WARNING): Not cleaning up dir /var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/bip68-sequence_224
2017-11-30 23:22:38.647000 TestFramework (ERROR): Test failed. Test logging available at /var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/bip68-sequence_224/test_framework.log


[1mstderr:
[0m

.......................................................................................................................................................
[1mtxn_doublespend.py[0m failed, Duration: 1 s

[1mstdout:
[0m/var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/txn_doublespend_218
2017-11-30 23:23:56.738000 TestFramework (INFO): Initializing test directory /var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/txn_doublespend_218
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
2017-11-30 23:23:57.181000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 256, in start_nodes
    node.wait_for_rpc_connection()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 87, in wait_for_rpc_connection
    assert self.process.poll() is None, "ravend exited with status %i during initialization" % self.process.returncode
AssertionError: ravend exited with status 1 during initialization

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 121, in main
    self.setup_network()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/txn_doublespend.py", line 21, in setup_network
    super().setup_network()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 200, in setup_network
    self.setup_nodes()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 215, in setup_nodes
    self.start_nodes()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 259, in start_nodes
    self.stop_nodes()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 275, in stop_nodes
    node.stop_node()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 120, in stop_node
    self.stop()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 69, in __getattr__
    assert self.rpc_connected and self.rpc is not None, "Error: no RPC connection"
AssertionError: Error: no RPC connection
2017-11-30 23:23:57.185000 TestFramework (INFO): Stopping nodes


[1mstderr:
[0mError: Unable to start HTTP server. See debug log for details.
Error: Unable to start HTTP server. See debug log for details.
Error: Unable to start HTTP server. See debug log for details.
Traceback (most recent call last):
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/txn_doublespend.py", line 143, in <module>
    TxnMallTest().main()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 145, in main
    self.stop_nodes()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 275, in stop_nodes
    node.stop_node()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 120, in stop_node
    self.stop()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 69, in __getattr__
    assert self.rpc_connected and self.rpc is not None, "Error: no RPC connection"
AssertionError: Error: no RPC connection


.
[1mtxn_clone.py --mineblock[0m failed, Duration: 1 s

[1mstdout:
[0m/var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/txn_clone_217
2017-11-30 23:23:57.722000 TestFramework (INFO): Initializing test directory /var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/txn_clone_217
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
2017-11-30 23:23:58.355000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 256, in start_nodes
    node.wait_for_rpc_connection()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 87, in wait_for_rpc_connection
    assert self.process.poll() is None, "ravend exited with status %i during initialization" % self.process.returncode
AssertionError: ravend exited with status 1 during initialization

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 121, in main
    self.setup_network()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/txn_clone.py", line 21, in setup_network
    super(TxnMallTest, self).setup_network()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 200, in setup_network
    self.setup_nodes()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 215, in setup_nodes
    self.start_nodes()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 259, in start_nodes
    self.stop_nodes()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 275, in stop_nodes
    node.stop_node()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 120, in stop_node
    self.stop()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 69, in __getattr__
    assert self.rpc_connected and self.rpc is not None, "Error: no RPC connection"
AssertionError: Error: no RPC connection
2017-11-30 23:23:58.355000 TestFramework (INFO): Stopping nodes


[1mstderr:
[0mError: Unable to start HTTP server. See debug log for details.
Traceback (most recent call last):
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/txn_clone.py", line 155, in <module>
    TxnMallTest().main()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 145, in main
    self.stop_nodes()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 275, in stop_nodes
    node.stop_node()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 120, in stop_node
    self.stop()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 69, in __getattr__
    assert self.rpc_connected and self.rpc is not None, "Error: no RPC connection"
AssertionError: Error: no RPC connection


......................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[1msegwit.py[0m failed, Duration: 9 s

[1mstdout:
[0m2017-11-30 23:27:42.061000 TestFramework (INFO): Initializing test directory /var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/segwit_210
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
2017-11-30 23:27:50.440000 TestFramework (INFO): Verify unsigned bare witness txs in versionbits-setting blocks are valid before the fork
2017-11-30 23:27:50.468000 TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 121, in main
    self.run_test()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/segwit.py", line 192, in run_test
    self.success_mine(self.nodes[2], wit_ids[NODE_2][WIT_V0][1], False) #block 428
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/segwit.py", line 92, in success_mine
    block = node.generate(1)
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/coverage.py", line 48, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/authproxy.py", line 138, in __call__
    raise JSONRPCException(response['error'])
test_framework.authproxy.JSONRPCException: CreateNewBlock: TestBlockValidity failed: block-validation-failed (code 16) (-1)
2017-11-30 23:27:50.471000 TestFramework (INFO): Stopping nodes
2017-11-30 23:27:51.068000 TestFramework (WARNING): Not cleaning up dir /var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/segwit_210
2017-11-30 23:27:51.068000 TestFramework (ERROR): Test failed. Test logging available at /var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/segwit_210/test_framework.log


[1mstderr:
[0m

.............................................
[1mfundrawtransaction.py[0m failed, Duration: 34 s

[1mstdout:
[0m2017-11-30 23:27:40.175000 TestFramework (INFO): Initializing test directory /var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/fundrawtransaction_211
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
2017-11-30 23:28:13.650000 TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 121, in main
    self.run_test()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/fundrawtransaction.py", line 584, in run_test
    result = self.nodes[3].fundrawtransaction(rawtx, {'includeWatching': True })
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/coverage.py", line 48, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/authproxy.py", line 138, in __call__
    raise JSONRPCException(response['error'])
test_framework.authproxy.JSONRPCException: Insufficient funds (-4)
2017-11-30 23:28:13.653000 TestFramework (INFO): Stopping nodes
2017-11-30 23:28:14.312000 TestFramework (WARNING): Not cleaning up dir /var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/fundrawtransaction_211
2017-11-30 23:28:14.313000 TestFramework (ERROR): Test failed. Test logging available at /var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/fundrawtransaction_211/test_framework.log


[1mstderr:
[0m

..
[1mwallet-accounts.py[0m failed, Duration: 1 s

[1mstdout:
[0m2017-11-30 23:28:14.927000 TestFramework (INFO): Initializing test directory /var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/wallet-accounts_208
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
2017-11-30 23:28:15.780000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 121, in main
    self.run_test()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/wallet-accounts.py", line 65, in run_test
    assert_equal(len(address_groups), 1)
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/util.py", line 39, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(2 == 1)
2017-11-30 23:28:15.781000 TestFramework (INFO): Stopping nodes
2017-11-30 23:28:16.098000 TestFramework (WARNING): Not cleaning up dir /var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/wallet-accounts_208
2017-11-30 23:28:16.098000 TestFramework (ERROR): Test failed. Test logging available at /var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/wallet-accounts_208/test_framework.log


[1mstderr:
[0m

.....................................................
[1mimportmulti.py[0m failed, Duration: 0 s

[1mstdout:
[0m2017-11-30 23:28:44.747000 TestFramework (INFO): Initializing test directory /var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/importmulti_204
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
2017-11-30 23:28:45.015000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 255, in start_nodes
    node.wait_for_rpc_connection()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 87, in wait_for_rpc_connection
    assert self.process.poll() is None, "ravend exited with status %i during initialization" % self.process.returncode
AssertionError: ravend exited with status 1 during initialization

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 120, in main
    self.setup_network()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/importmulti.py", line 16, in setup_network
    self.setup_nodes()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 214, in setup_nodes
    self.start_nodes()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 258, in start_nodes
    self.stop_nodes()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 274, in stop_nodes
    node.stop_node()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 120, in stop_node
    self.stop()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 69, in __getattr__
    assert self.rpc_connected and self.rpc is not None, "Error: no RPC connection"
AssertionError: Error: no RPC connection
2017-11-30 23:28:45.035000 TestFramework (INFO): Stopping nodes


[1mstderr:
[0mError: Unable to start HTTP server. See debug log for details.
Traceback (most recent call last):
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/importmulti.py", line 451, in <module>
    ImportMultiTest ().main ()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 144, in main
    self.stop_nodes()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 274, in stop_nodes
    node.stop_node()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 120, in stop_node
    self.stop()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 69, in __getattr__
    assert self.rpc_connected and self.rpc is not None, "Error: no RPC connection"
AssertionError: Error: no RPC connection


.......................................................
[1mwallet.py[0m failed, Duration: 83 s

[1mstdout:
[0m2017-11-30 23:27:51.674000 TestFramework (INFO): Initializing test directory /var/folders/mk/gcvg496x2dxd2qb3hl5fn3m80000gn/T/raven_test_runner_20171130_162205/wallet_209
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
2017-11-30 23:27:53.902000 TestFramework (INFO): Mining blocks...
2017-11-30 23:27:54.289000 TestFramework (INFO): test gettxout
2017-11-30 23:27:54.291000 TestFramework (INFO): test getmemoryinfo
2017-11-30 23:27:54.509000 TestFramework (INFO): test gettxout (second part)
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
2017-11-30 23:28:10.627000 TestFramework (INFO): check -rescan
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
2017-11-30 23:28:12.656000 TestFramework (INFO): check -reindex
HGB: 48218f3664485e3e9798a09b24250625791c51d94ad2d278933ba8ce8b5a2a9b
HGR: a4c84e05d4f74f0df5e69a8c2e85524f9776555980a60312ab0fd524cd9b1474
2017-11-30 23:29:15.018000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 121, in main
    self.run_test()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/wallet.py", line 366, in run_test
    self.start_node(0, [m, "-limitancestorcount="+str(chainlimit)])
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 240, in start_node
    node.wait_for_rpc_connection()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 106, in wait_for_rpc_connection
    raise AssertionError("Unable to connect to ravend")
AssertionError: Unable to connect to ravend
2017-11-30 23:29:15.023000 TestFramework (INFO): Stopping nodes


[1mstderr:
[0mTraceback (most recent call last):
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/wallet.py", line 433, in <module>
    WalletTest().main()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 144, in main
    self.stop_nodes()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_framework.py", line 274, in stop_nodes
    node.stop_node()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 120, in stop_node
    self.stop()
  File "/Users/tperkins/eclipse-workspace/raven/test/functional/test_framework/test_node.py", line 69, in __getattr__
    assert self.rpc_connected and self.rpc is not None, "Error: no RPC connection"
AssertionError: Error: no RPC connection


..........................................